### ISSUE TITLE
Most recent branch

### ISSUE THREAD

**Issue by mdifonzo** [jim-easterbrook/python-gphoto2#5]
I'm not sure exactly when this happened, but my examples no longer work with the latest build - here is the issue that I ran into:

This is what I have in my branch:
def gp_camera_capture(*args):
  """
    gp_camera_capture(camera, type, path, context) -> int

```
Parameters:
    camera: Camera *
    type: enum CameraCaptureType
    path: CameraFilePath *
    context: GPContext *

"""
```

  return _gphoto2_camera.gp_camera_capture(*args)

The "path: CameraFilePath *" no longer exists when I run in your latest version, so I can't make use of the capture / trigger_capture functions anymore.

Thanks,
Matt
